version: '3.8'

services:
  dev-db:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./src/main/resources/application.properties
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '/home/jun/db/lost/dev/mysql:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_ROOT_PASSWORD}" ]
      retries: 3
      timeout: 5s
  test-db:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT:-3307}:3306'
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./src/test/resources/application.properties
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '/home/jun/db/lost/test/mysql:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_ROOT_PASSWORD}" ]
      retries: 3
      timeout: 5s
#  dev-mdb:
#     image: redis:latest
#     restart: always
#     ports:
#       - '6379:6379'
#     volumes:
#       - '/home/jun/db/lost/dev/redis:/data'
#     healthcheck:
#       test: [ "CMD", "redis-cli", "ping" ]
#       retries: 3
#       timeout: 5s