spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  session:
    storeType: jdbc
    jdbc:
      tableName: SPRING_SESSION
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      initializeSchema: always
server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
      cookie:
        max-age: 1800
        httpOnly: true
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB
#        sameSite: strict
#        secure: true
#        domain: localhost

env:
  client-url: ${CLIENT_URL}

storage:
  image-config:
    root-location: ${IMAGE_ROOT_LOCATION}
    base-url: ${IMAGE_BASE_URL}