spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  session:
    storeType: jdbc
    jdbc:
      tableName: SPRING_SESSION
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      initializeSchema: always
server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
      cookie:
        max-age: 1800
        httpOnly: true
    multipart:
      enabled: true
      location: /home/jun/dev/lost/src/main/resources/tmp
      max-file-size: 128KB
      max-request-size: 128KB
#        sameSite: strict
#        secure: true
#        domain: localhost

env:
  client-url: http://localhost:3000

storage:
  image-config:
    root-location: src/main/resources/uploads
    base-url: http://localhost:8080/uploads/images
    resource-path: classpath*:uploads/**