package com.lost.fake;

import com.lost.image.domain.PostImage;
import com.lost.image.service.repository.ImagePostRepository;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeImagePostRepository implements ImagePostRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(1L);
    private final List<PostImage> data = new ArrayList<>();

    @Override
    public Image save(Image image) {
        Long imageId = image.getId();
        if (imageId == null) {
            image = Image.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .url(image.getUrl())
                    .fileName(image.getFileName())
                    .originalFileName(image.getOriginalFileName())
                    .createdAt(image.getCreatedAt())
                    .updatedAt(image.getUpdatedAt())
                    .build();
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), imageId));
        }
        data.add(PostImage.from(image, null));
        return image;
    }

    @Override
    public Optional<Image> findById(Long imageId) {
        return data.stream()
                .filter(image -> image.getId().equals(imageId))
                .findAny()
                .map(PostImage::toModel);
    }

    @Override
    public List<PostImage> saveAll(List<PostImage> postImageJpaEntities) {
        List<PostImage> result = new ArrayList<>();
        for (PostImage postImageJpaEntity : postImageJpaEntities) {
            Image image = save(postImageJpaEntity.toModel());
            result.add(PostImage.from(image, postImageJpaEntity.getPost()));
        }
        return result;
    }
}
